### ISSUE TITLE
pin only lower bound of required providers

### ISSUE THREAD

**Issue by hall** [expel-io/terraform-aws-eks#11]
**Is your feature request related to a problem? Please describe.**

As suggested in [Terraform's docs on module version constraints](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions), reusable modules should only pin lower bounds to avoid incompatibilities.

**Describe the solution you'd like**

The `aws` provider should constrain only the lower version instead of being pinned to a specific major version.

**Describe alternatives you've considered**

The only alternative I'm aware of is just bumping the provider version across all other modules consumed by a root module (however, that's not always possible without having ownership over every module).

**Additional context**

I don't know which version of the `aws` provider is appropriate to use.

**Comment by bachu20** [comment]
@hall Thanks for calling this out. We'll put out an update to adhere to the recommended standards.
